//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscuelaForm.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clases()
        {
            this.Asistencia = new HashSet<Asistencia>();
        }
    
        public int id_clase { get; set; }
        public int id_tipocancelacion { get; set; }
        public int id_horario { get; set; }
        public int id_tipotarea { get; set; }
        public int id_profesor { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.TimeSpan> hora_inicio { get; set; }
        public Nullable<System.TimeSpan> hora_fin { get; set; }
        public string notas_pedagogicas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asistencia> Asistencia { get; set; }
        public virtual Horarios Horarios { get; set; }
        public virtual Profesores Profesores { get; set; }
        public virtual Tipos_de_cancelacion Tipos_de_cancelacion { get; set; }
        public virtual Tipos_de_tarea Tipos_de_tarea { get; set; }
    }
}
