//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscuelaForm.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupos()
        {
            this.Horarios = new HashSet<Horarios>();
            this.Aulas = new HashSet<Aulas>();
        }
    
        public int id_grupo { get; set; }
        public Nullable<int> id_profesor { get; set; }
        public Nullable<int> id_curso { get; set; }
        public string nombre { get; set; }
        public string codigo { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public string lugar { get; set; }
        public string notas { get; set; }
        public string horario { get; set; }
        public Nullable<int> maximo_alumnos { get; set; }
        public Nullable<int> numero_alumnos { get; set; }
        public Nullable<int> id_aula { get; set; }
    
        public virtual Cursos Cursos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horarios> Horarios { get; set; }
        public virtual Profesores Profesores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aulas> Aulas { get; set; }
    }
}
