//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscuelaForm.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Horarios()
        {
            this.Clases = new HashSet<Clases>();
        }
    
        public int id_horario { get; set; }
        public int id_profesor { get; set; }
        public int id_grupo { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<bool> L { get; set; }
        public Nullable<bool> M { get; set; }
        public Nullable<bool> X { get; set; }
        public Nullable<bool> J { get; set; }
        public Nullable<bool> V { get; set; }
        public System.TimeSpan hora_inicio { get; set; }
        public System.TimeSpan hora_fin { get; set; }
        public int id_tipo_tarea { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clases> Clases { get; set; }
        public virtual Grupos Grupos { get; set; }
        public virtual Profesores Profesores { get; set; }
        public virtual Profesores Profesores1 { get; set; }
        public virtual Tipos_de_tarea Tipos_de_tarea { get; set; }
    }
}
