//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscuelaForm.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matriculas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Matriculas()
        {
            this.Alumnos_en_grupos = new HashSet<Alumnos_en_grupos>();
        }
    
        public int id_matricula { get; set; }
        public int id_curso { get; set; }
        public int id_alumno { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumnos_en_grupos> Alumnos_en_grupos { get; set; }
        public virtual Cursos Cursos { get; set; }
    }
}
